import os

basedir = os.path.abspath(os.path.dirname(__file__))

WTF_CSRF_ENABLED = True
SECRET_KEY = "Hard to Guess"

SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir,'foo.db')
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECURITY_BLUEPRINT_NAME = 'auth'
SECURITY_URL_PREFIX = '/auth'
SECURITY_FLASH_MESSAGES = True
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = 'hdsljdfurhfjvn'
SECURITY_EMAIL_SENDER = None
SECURITY_TOKEN_AUTHENTICATION_KEY = 'auth-token'
SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'
SECURITY_TOKEN_MAX_AGE = None
SECURITY_DEFAULT_HTTP_AUTH_REALM = 'Login Required'

SECURITY_CONFIRMABLE = False
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = False	
SECURITY_TRACKABLE = False
SECURITY_PASSWORDLESS = False
SECURITY_CHANGEABLE = True

# configure to True when mail is set up 

SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False
SECURITY_CONFIRM_EMAIL_WITHIN = 5
SECURITY_RESET_PASSWORD_WITHIN = 5 
SECURITY_LOGIN_WITHIN = 1
SECURITY_LOGIN_WITHOUT_CONFIRMATION =False
SECURITY_DEFAULT_REMEMBER_ME = False


SECURITY_LOGIN_URL = '/login'
SECURITY_LOGOUT_URL = '/logout'
SECURITY_REGISTER_URL = '/register'
SECURITY_POST_LOGIN_VIEW = '/'


SECURITY_LOGIN_USER_TEMPLATE = '/security/login_user.html'
SECURITY_REGISTER_USER_TEMPLATE = '/security/register_user.html'
